import React, { Component } from "react";
import { render } from "react-dom";
import SortableTree from "react-sortable-tree";

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      treeData: [ { code: '|1',
    title: 'Start',
    call_fxn: 'checkIfExist',
    call_params: 'msisdn',
    middleware: undefined,
    menu: undefined,
    children:
     [ { code: '|1|1',
         title:
          '[iff] Welcome to MARAFIKI. By registering you are agreeing to MARAFIKI terms and conditions. \n1. Continue',
         call_fxn: '',
         call_params: '',
         middleware: undefined,
         menu: undefined,
         children:
          [ { code: '|1|1|1',
              title: 'Enter ID number or Passport',
              call_fxn: '',
              call_params: 'id_number[*]',
              middleware: undefined,
              menu: undefined,
              children:
               [ { code: '|1|1|1|1',
                   title: 'Full names as per ID or Passport',
                   call_fxn: '',
                   call_params: 'name[*]',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|1|1|1|1',
                        title: 'Set PIN number',
                        call_fxn: '',
                        call_params: 'pin[*]',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|1|1|1|1|1',
                             title: 'Confirm PIN number',
                             call_fxn: 'register',
                             call_params: 'id_number|name|pin|confirm_pin[*]',
                             middleware: undefined,
                             menu: undefined,
                             children: [] } ] } ] } ] } ] },
       { code: '|1|2',
         title:
          '[iff] Goodii Afternoon. \nEnter Marafiki PIN NUMBER to access Lenders and Borrowers services from Mobipesa Limited. Customer care: 0703012300.',
         call_fxn: 'login',
         call_params: 'msisdn|pin[*]',
         middleware: 'auth',
         menu: '0',
         children:
          [ { code: '|1|2|1',
              title: 'Lender',
              call_fxn: '',
              call_params: '',
              middleware: undefined,
              menu: undefined,
              children:
               [ { code: '|1|2|1|1',
                   title: 'INVITE Customers',
                   call_fxn: '',
                   call_params: '',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|1|1|1',
                        title: 'INVITE Customers',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|1|1|1|1',
                             title:
                              'What is the phone number of the customer that you are INVITING into your network?',
                             call_fxn: '',
                             call_params: 'customer_msisdn[*]',
                             middleware: undefined,
                             menu: undefined,
                             children:
                              [ { code: '|1|2|1|1|1|1|1',
                                  title:
                                   '&Confirm you are inviting ${customer_msisdn} to be your FLEXI-LOAN customer',
                                  call_fxn: '',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] },
                                { code: '|1|2|1|1|1|1|2',
                                  title: 'Yes',
                                  call_fxn: 'invite_customer',
                                  call_params: 'customer_msisdn|msisdn',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] },
                                { code: '|1|2|1|1|1|1|3',
                                  title: 'Cancel',
                                  call_fxn: 'CANCEL',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] } ] } ] },
                      { code: '|1|2|1|1|2',
                        title: 'REGISTER Agents',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|1|1|2|1',
                             title: 'Enter the AGENT’S MOBILE Number',
                             call_fxn: '',
                             call_params: 'agent_msisdn[*]',
                             middleware: undefined,
                             menu: undefined,
                             children:
                              [ { code: '|1|2|1|1|2|1|1',
                                  title:
                                   '&Confirm you are inviting ${agent_msisdn} to be your FLEXI-LOAN Customers’ AGENT',
                                  call_fxn: '',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] },
                                { code: '|1|2|1|1|2|1|2',
                                  title: 'Yes',
                                  call_fxn: 'invite_agent',
                                  call_params: 'agent_msisdn|msisdn',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] },
                                { code: '|1|2|1|1|2|1|3',
                                  title: 'Cancel',
                                  call_fxn: 'CANCEL',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] } ] } ] },
                      { code: '|1|2|1|1|3',
                        title: 'INTRODUCE Customers to LENDERS',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|1|1|3|1',
                             title: 'Enter customer’s MOBILE Number',
                             call_fxn: '',
                             call_params: 'customer_mobile_no[*]',
                             middleware: undefined,
                             menu: undefined,
                             children:
                              [ { code: '|1|2|1|1|3|1|1',
                                  title: 'Enter AGENT’S MOBILE Number',
                                  call_fxn: '',
                                  call_params: 'agent_mobile_no[*]',
                                  middleware: undefined,
                                  menu: undefined,
                                  children:
                                   [ { code: '|1|2|1|1|3|1|1|1',
                                       title:
                                        '&Confirm you are introducing ${agent_mobile_no} as an agent for customer ${customer_mobile_no}',
                                       call_fxn: '',
                                       call_params: '',
                                       middleware: undefined,
                                       menu: undefined,
                                       children: [] },
                                     { code: '|1|2|1|1|3|1|1|2',
                                       title: 'Yes',
                                       call_fxn: 'introduce_customer_to_lenders',
                                       call_params: 'agent_mobile_no|customer_mobile_no|msisdn',
                                       middleware: undefined,
                                       menu: undefined,
                                       children: [] },
                                     { code: '|1|2|1|1|3|1|1|3',
                                       title: 'Cancel',
                                       call_fxn: 'CANCEL',
                                       call_params: '',
                                       middleware: undefined,
                                       menu: undefined,
                                       children: [] } ] } ] } ] } ] },
                 { code: '|1|2|1|2',
                   title: 'Approve public loans',
                   call_fxn: 'get_lenders_approve_loan_public_list',
                   call_params: '',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|1|2|1',
                        title: '&Approve the loans below',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children: [] },
                      { code: '|1|2|1|2|2',
                        title:
                         '$$$ ${_name} – ${_period} loan – Kshs ${_amount} at ${_percentage}',
                        call_fxn: '',
                        call_params: '_reference_id[*]',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|1|2|2|1',
                             title:
                              '&Confirm that you are LENDING a ${_period} loan of Kshs ${_amount} to ${_name}, and that YOU WILL collect the loan instalment from him/her',
                             call_fxn: '',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|1|2|2|2',
                             title: 'Yes',
                             call_fxn: 'approve_public_lender_loan',
                             call_params: '_name|_period|_amount|_percentage|_reference_id',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|1|2|2|3',
                             title: 'Cancel',
                             call_fxn: 'CANCEL',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] } ] } ] },
                 { code: '|1|2|1|3',
                   title: 'Approve private loans',
                   call_fxn: 'get_lenders_approve_loan_private_list',
                   call_params: '',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|1|3|1',
                        title: '&Approve the loans below',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children: [] },
                      { code: '|1|2|1|3|2',
                        title:
                         '$$$ ${_name} – ${_period} loan – Kshs ${_amount} at ${_percentage}',
                        call_fxn: '',
                        call_params: '_reference_id[*]',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|1|3|2|1',
                             title:
                              '&Confirm that you are LENDING a ${_period} loan of Kshs ${_amount} to ${_name}, and that YOU WILL collect the loan instalment from him/her',
                             call_fxn: '',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|1|3|2|2',
                             title: 'Yes',
                             call_fxn: 'approve_private_lender_loan',
                             call_params: '_name|_period|_amount|_percentage|_reference_id',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|1|3|2|3',
                             title: 'Cancel',
                             call_fxn: 'CANCEL',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] } ] } ] },
                 { code: '|1|2|1|4',
                   title: 'SELECT SET INTEREST RATE',
                   call_fxn: 'get_lender_current_interest_rate',
                   call_params: '_current_lender_interest_rate[*]',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|1|4|1',
                        title:
                         'Your lending interest rate is ${_current_interest_rate}. What is the new INTEREST RATE to be set for PRIVATE LOANS?',
                        call_fxn: '',
                        call_params: 'new_lender_interest_rate',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|1|4|1|1',
                             title:
                              'Confirm that you are setting your PRIVATE LENDING RATE at 20%.',
                             call_fxn: '',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|1|4|1|2',
                             title: 'Yes',
                             call_fxn: 'change_lender_interest_rate',
                             call_params: 'new_lender_interest_rate|msisdn',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|1|4|1|3',
                             title: 'Cancel',
                             call_fxn: 'CANCEL',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] } ] } ] },
                 { code: '|1|2|1|5',
                   title: 'Mahitaji Credit',
                   call_fxn: '',
                   call_params: '',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|1|5|1',
                        title: '&Approve Mahitaji credit below',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children: [] },
                      { code: '|1|2|1|5|2',
                        title: '$$$ ${_name} –  Kshs ${_amount} at ${_percentage}',
                        call_fxn: '',
                        call_params: '_mahitaji_reference_id[*]',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|1|5|2|1',
                             title:
                              'Confirm that you are LENDING a MAHITAJI CREDIT of Kshs ${_amount} at ${_percentage} to JOHN DOE',
                             call_fxn: '',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|1|5|2|2',
                             title: 'Yes',
                             call_fxn: 'approve_lender_mahitaji_credit',
                             call_params: '_mahitaji_reference_id|msisdn',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|1|5|2|3',
                             title: 'Cancel',
                             call_fxn: 'CANCEL',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] } ] } ] },
                 { code: '|1|2|1|6',
                   title: 'Check Balance',
                   call_fxn: 'lender_check_balance',
                   call_params: 'msisdn',
                   middleware: undefined,
                   menu: undefined,
                   children: [] },
                 { code: '|1|2|1|7',
                   title: 'Change PIN',
                   call_fxn: '',
                   call_params: '',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|1|7|1',
                        title: 'What is your CURRENT PIN number?',
                        call_fxn: '',
                        call_params: 'current_pin[*]',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|1|7|1|1',
                             title: 'Enter NEW PIN Number:',
                             call_fxn: '',
                             call_params: 'new_pin[*]',
                             middleware: undefined,
                             menu: undefined,
                             children:
                              [ { code: '|1|2|1|7|1|1|1',
                                  title: 'Enter NEW PIN Number again to confirm it:',
                                  call_fxn: 'change_lender_pin',
                                  call_params: 'confirm_new_pin[*]',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] } ] } ] } ] } ] },
            { code: '|1|2|2',
              title: 'Borrower',
              call_fxn: '',
              call_params: '',
              middleware: undefined,
              menu: undefined,
              children:
               [ { code: '|1|2|2|1',
                   title: 'INVITE Friends',
                   call_fxn: '',
                   call_params: '',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|2|1|1',
                        title: 'My network',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|2|1|1|1',
                             title:
                              'What is the phone number of the customer that you are INVITING into your network?',
                             call_fxn: '',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children:
                              [ { code: '|1|2|2|1|1|1|1',
                                  title:
                                   'Confirm you are inviting ${INPUT:1} to be your FLEXI-LOAN customer',
                                  call_fxn: '',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children:
                                   [ { code: '|1|2|2|1|1|1|1|1',
                                       title: 'Yes',
                                       call_fxn: '',
                                       call_params: '',
                                       middleware: undefined,
                                       menu: undefined,
                                       children:
                                        [ { code: '|1|2|2|1|1|1|1|1|1',
                                            title: 'Your friend’s request has been sent to ${INPUT:3}',
                                            call_fxn: undefined,
                                            call_params: undefined,
                                            middleware: undefined,
                                            menu: undefined,
                                            children: [] } ] },
                                     { code: '|1|2|2|1|1|1|1|2',
                                       title: 'Cancel',
                                       call_fxn: undefined,
                                       call_params: undefined,
                                       middleware: undefined,
                                       menu: undefined,
                                       children: [] } ] } ] } ] },
                      { code: '|1|2|2|1|2',
                        title: 'Agency Network',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|2|1|2|1',
                             title:
                              'You need to be a LENDER’S AGENT for you to INTRODUCE a customer to the Lender. Are you any LENDER’S AGENT?',
                             call_fxn: '',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|2|1|2|2',
                             title: 'YES',
                             call_fxn: '',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children:
                              [ { code: '|1|2|2|1|2|2|1',
                                  title: 'Enter lender’s MOBILE NUMBER',
                                  call_fxn: '',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children:
                                   [ { code: '|1|2|2|1|2|2|1|1',
                                       title: 'Enter customer’s MOBILE NUMBER',
                                       call_fxn: '',
                                       call_params: '',
                                       middleware: undefined,
                                       menu: undefined,
                                       children:
                                        [ { code: '|1|2|2|1|2|2|1|1|1',
                                            title:
                                             'Confirm that you are inviting the CUSTOMER 0727362016 through your AGENCY to the LENDER 0718401726?',
                                            call_fxn: '',
                                            call_params: '',
                                            middleware: undefined,
                                            menu: undefined,
                                            children:
                                             [ { code: '|1|2|2|1|2|2|1|1|1|1',
                                                 title: 'Yes',
                                                 call_fxn: '',
                                                 call_params: '',
                                                 middleware: undefined,
                                                 menu: undefined,
                                                 children:
                                                  [ { code: '|1|2|2|1|2|2|1|1|1|1|1',
                                                      title:
                                                       'Your request for introduction of CUSTOMER 0727362016 to LENDER 0718401726 has been queued for processing',
                                                      call_fxn: undefined,
                                                      call_params: undefined,
                                                      middleware: undefined,
                                                      menu: undefined,
                                                      children: [] } ] },
                                               { code: '|1|2|2|1|2|2|1|1|1|2',
                                                 title: 'Cancel',
                                                 call_fxn: undefined,
                                                 call_params: undefined,
                                                 middleware: undefined,
                                                 menu: undefined,
                                                 children: [] } ] } ] } ] } ] } ] } ] },
                 { code: '|1|2|2|2',
                   title: 'Apply loan',
                   call_fxn: '',
                   call_params: '',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|2|2|1',
                        title:
                         '&Continue if you agree LENDERS can access your CRB LOAN HISTORY. MAXIMUM loan limit: Kshs 2,000.00',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children: [] },
                      { code: '|1|2|2|2|2',
                        title: 'YES',
                        call_fxn: 'get_borrower_loan_days',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|2|2|2|1',
                             title: '&SELECT LOAN PERIOD',
                             call_fxn: '',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|2|2|2|2',
                             title: '$$$ ${_borrower_loan_period} Days',
                             call_fxn: '',
                             call_params: 'selected_borrower_loan_reference_id[*]',
                             middleware: undefined,
                             menu: undefined,
                             children:
                              [ { code: '|1|2|2|2|2|2|1',
                                  title:
                                   '&If APPROVED, you will receive Kshs ${_amount} after mpesa deduction fee: ${_deduction_amount}. Do you wish to proceed?',
                                  call_fxn: '',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] },
                                { code: '|1|2|2|2|2|2|2',
                                  title: 'YES',
                                  call_fxn: 'borrower_request_loan',
                                  call_params: 'selected_borrower_loan_reference_id|msisdn',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] },
                                { code: '|1|2|2|2|2|2|3',
                                  title: 'Cancel',
                                  call_fxn: 'CANCEL',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] } ] } ] },
                      { code: '|1|2|2|2|3',
                        title: 'Cancel',
                        call_fxn: 'CANCEL',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children: [] } ] },
                 { code: '|1|2|2|3',
                   title: 'Pay loan',
                   call_fxn: 'get_borrower_existing_loan',
                   call_params: '',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|2|3|1',
                        title:
                         'Would you like to pay your loan balance of Kshs ${_get_borrower_existing_loan} from mpesa?',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children: [] },
                      { code: '|1|2|2|3|2',
                        title: 'YES',
                        call_fxn: '',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|2|3|2|1',
                             title: 'Enter your service PIN (Forgot PIN? Answer with 0)',
                             call_fxn: '',
                             call_params: 'service_pin[*]',
                             middleware: undefined,
                             menu: undefined,
                             children:
                              [ { code: '|1|2|2|3|2|1|1',
                                  title:
                                   'Enter amount. Mpesa allows amount between Kshs 10 and Kshs 70,000.00',
                                  call_fxn: '',
                                  call_params: 'payoff_amount[*]',
                                  middleware: undefined,
                                  menu: undefined,
                                  children:
                                   [ { code: '|1|2|2|3|2|1|1|1',
                                       title: '&Loan payoff of Kshs ${_amount}. Do you wish to proceed?',
                                       call_fxn: '',
                                       call_params: '',
                                       middleware: undefined,
                                       menu: undefined,
                                       children: [] },
                                     { code: '|1|2|2|3|2|1|1|2',
                                       title: 'YES',
                                       call_fxn: 'repay_borrower_loan',
                                       call_params: 'service_pin|payoff_msisdn|msisdn',
                                       middleware: undefined,
                                       menu: undefined,
                                       children: [] },
                                     { code: '|1|2|2|3|2|1|1|3',
                                       title: 'Cancel',
                                       call_fxn: 'CANCEL',
                                       call_params: '',
                                       middleware: undefined,
                                       menu: undefined,
                                       children: [] } ] } ] } ] },
                      { code: '|1|2|2|3|3',
                        title: 'Cancel',
                        call_fxn: 'CANCEL',
                        call_params: '',
                        middleware: undefined,
                        menu: undefined,
                        children: [] } ] },
                 { code: '|1|2|2|4',
                   title: 'Mahitaji credit',
                   call_fxn: '',
                   call_params: '',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|2|4|1',
                        title: 'Enter amount you wish to apply for. MAXIMUM Kshs ****',
                        call_fxn: '',
                        call_params: 'borrower_mahitagi_credit[*]',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|2|4|1|1',
                             title: '&Select daily interest rate group:',
                             call_fxn: '',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children: [] },
                           { code: '|1|2|2|4|1|2',
                             title: '$$$ ${_percentage}%',
                             call_fxn: '',
                             call_params: '',
                             middleware: undefined,
                             menu: undefined,
                             children:
                              [ { code: '|1|2|2|4|1|2|1',
                                  title:
                                   'Confirm that you are applying for MAHITAJI CREDIT of Kshs **** at daily interest of 0.67%',
                                  call_fxn: '',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] },
                                { code: '|1|2|2|4|1|2|2',
                                  title: 'YES',
                                  call_fxn: 'mahitagi_borrower_loan_request',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] },
                                { code: '|1|2|2|4|1|2|3',
                                  title: 'Cancel',
                                  call_fxn: 'CANCEL',
                                  call_params: '',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] } ] } ] } ] },
                 { code: '|1|2|2|5',
                   title: 'Change PIN',
                   call_fxn: '',
                   call_params: '',
                   middleware: undefined,
                   menu: undefined,
                   children:
                    [ { code: '|1|2|2|5|1',
                        title: 'What is your CURRENT PIN number?',
                        call_fxn: '',
                        call_params: 'current_pin[*]',
                        middleware: undefined,
                        menu: undefined,
                        children:
                         [ { code: '|1|2|2|5|1|1',
                             title: 'Enter NEW PIN Number:',
                             call_fxn: '',
                             call_params: 'new_pin[*]',
                             middleware: undefined,
                             menu: undefined,
                             children:
                              [ { code: '|1|2|2|5|1|1|1',
                                  title: 'Enter NEW PIN Number again to confirm it:',
                                  call_fxn: 'change_lender_pin',
                                  call_params: 'confirm_new_pin[*]',
                                  middleware: undefined,
                                  menu: undefined,
                                  children: [] } ] } ] } ] } ] } ] } ] } ]
    };
  }

  render() {
    return (
      <div style={{ height: 5000 }}>
        <SortableTree
          treeData={this.state.treeData}
          onChange={treeData => this.setState({ treeData })}
        />
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));
